/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Usuario;
import Utils.Util;
import controller.UsuarioController;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class FrAltUsuario extends javax.swing.JDialog {

    private int pkUsuario;

    /**
     * Creates new form FrAltUsuario
     */
    public FrAltUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setPkUsuario(int pkUsuario) {
        this.pkUsuario = pkUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        edtSenha = new javax.swing.JPasswordField();
        edtDataNasc = new javax.swing.JFormattedTextField();
        edtEmail = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        chkAtivo = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblConfirmeSenha = new javax.swing.JLabel();
        edtConfirmeSenha = new javax.swing.JPasswordField();
        edtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        btnAlterarSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alteração de Usuário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3017938_adapt_alter_compose_correct_edit_icon.png"))); // NOI18N
        jLabel1.setText("Alterar Usuário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lblNome.setBackground(new java.awt.Color(0, 0, 0));
        lblNome.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        lblEmail.setBackground(new java.awt.Color(0, 0, 0));
        lblEmail.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblSenha.setBackground(new java.awt.Color(0, 0, 0));
        lblSenha.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSenha.setText("Senha");
        jPanel1.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        lblDataNasc.setBackground(new java.awt.Color(0, 0, 0));
        lblDataNasc.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblDataNasc.setForeground(new java.awt.Color(0, 0, 0));
        lblDataNasc.setText("Data de Nascimento");
        jPanel1.add(lblDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        edtSenha.setEditable(false);
        edtSenha.setBackground(java.awt.Color.gray);
        edtSenha.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        edtSenha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 168, -1));

        edtDataNasc.setBackground(new java.awt.Color(255, 255, 255));
        edtDataNasc.setForeground(new java.awt.Color(0, 0, 0));
        edtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jPanel1.add(edtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 408, 29));

        edtEmail.setBackground(new java.awt.Color(255, 255, 255));
        edtEmail.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        edtEmail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 408, -1));

        edtNome.setBackground(new java.awt.Color(255, 255, 255));
        edtNome.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        edtNome.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 408, -1));

        chkAtivo.setBackground(new java.awt.Color(255, 102, 102));
        chkAtivo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        chkAtivo.setForeground(new java.awt.Color(0, 0, 0));
        chkAtivo.setText("Ativo");
        chkAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtivoActionPerformed(evt);
            }
        });
        jPanel1.add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 404, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1398919_close_cross_incorrect_invalid_x_icon.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 50));
        btnCancelar.setMinimumSize(new java.awt.Dimension(100, 50));
        btnCancelar.setPreferredSize(new java.awt.Dimension(150, 50));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 435, 175, -1));

        btnSalvar.setBackground(new java.awt.Color(0, 255, 0));
        btnSalvar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1398911_correct_mark_success_tick_valid_icon.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setMaximumSize(new java.awt.Dimension(100, 50));
        btnSalvar.setMinimumSize(new java.awt.Dimension(100, 50));
        btnSalvar.setPreferredSize(new java.awt.Dimension(150, 50));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 435, 174, -1));

        lblConfirmeSenha.setBackground(new java.awt.Color(0, 0, 0));
        lblConfirmeSenha.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblConfirmeSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblConfirmeSenha.setText("Repetir Senha");
        jPanel1.add(lblConfirmeSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        edtConfirmeSenha.setEditable(false);
        edtConfirmeSenha.setBackground(java.awt.Color.gray);
        edtConfirmeSenha.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        edtConfirmeSenha.setForeground(new java.awt.Color(0, 0, 0));
        edtConfirmeSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtConfirmeSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(edtConfirmeSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 168, 30));

        edtCodigo.setEditable(false);
        edtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        edtCodigo.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        edtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, -1));

        lblCodigo.setBackground(new java.awt.Color(0, 0, 0));
        lblCodigo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("Código");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnAlterarSenha.setBackground(new java.awt.Color(255, 255, 102));
        btnAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/47947_edit_modification_pen_pencil_write_icon.png"))); // NOI18N
        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarSenhaMouseClicked(evt);
            }
        });
        jPanel1.add(btnAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAtivoActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void edtConfirmeSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtConfirmeSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtConfirmeSenhaActionPerformed

    private void btnAlterarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarSenhaMouseClicked
        if (edtSenha.isEditable()) {
            edtSenha.setEditable(false);
            edtConfirmeSenha.setEditable(false);
            edtSenha.setBackground(Color.GRAY);
            edtConfirmeSenha.setBackground(Color.GRAY);

            edtSenha.setText("");
            edtConfirmeSenha.setText("");
            btnAlterarSenha.setText("");

            btnAlterarSenha.setText("Alterar Senha");
        } else {
            edtSenha.setEditable(true);
            edtConfirmeSenha.setEditable(true);
            edtSenha.setBackground(Color.WHITE);
            edtConfirmeSenha.setBackground(Color.WHITE);

            btnAlterarSenha.setText("Cancelar");
        }
    }//GEN-LAST:event_btnAlterarSenhaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(Util.getIcone());

        // Carregar dados do usuário
        UsuarioController controller = new UsuarioController();

        List<Usuario> lista = controller.consultar(0, String.valueOf(pkUsuario));

        Usuario usu = lista.get(0);

        // Preencher os campos como a variavel usu
        edtCodigo.setText(String.valueOf(usu.getPkUsuario()));
        edtNome.setText(usu.getNome());
        edtEmail.setText(usu.getEmail());

        edtDataNasc.setText(Util.converterDateToString(usu.getDataNascimento()));
        chkAtivo.setSelected(usu.isAtivo());
    }//GEN-LAST:event_formWindowOpened
    private void gravar() {
        //validar o preenchimento dos campos
        if (!verificarCampos()) {
            return;
        }
        //ler os campos e guardar um objeto
        Usuario usu = new Usuario();
        usu.setPkUsuario(Integer.parseInt(edtCodigo.getText()));
        usu.setNome(edtNome.getText());
        usu.setEmail(edtEmail.getText());
        if (edtSenha.isEditable()) {
            usu.setSenha(Util.calcularHash(new String(edtSenha.getPassword())));
        }
        usu.setDataNascimento(Util.converterStringToDate(edtDataNasc.getText()));
        usu.setAtivo(chkAtivo.isSelected());
        // enviar para o banco de dados

        UsuarioController controller = new UsuarioController();
        if (controller.alterar(usu)) {
            JOptionPane.showMessageDialog(null, "Usuário alterado");
            this.dispose();
        }

    }

    private boolean verificarCampos() {
        if (edtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'Nome' em branco");
            return false;
        }

        if (edtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'E-mail' em branco");
            return false;
        }
        if (edtSenha.isEditable()) {
            if (new String(edtSenha.getPassword()).isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo 'Senha' em branco)");
                return false;
            }
        }
        //^ - inicio de linha
        //$ - final de linha
        //[] - conjunto de caracteres
        //+ - quantidade de vezes que o conjunto pode aparecer
        //+ - 1 ou mais vezes
        //* - 0 ou mais vezes
        //{5} - 5 vezes
        //{2} - 2 vezes
        if (!edtNome.getText().matches("^[\\p{L} ]+$")) {
            JOptionPane.showMessageDialog(null, "O campo 'Nome' possui formato inválido");
            return false;
        }
        if (!edtEmail.getText().matches("^[a-z0-9_.]+@[a-z0-9_.]+.[a-z]+$")) {
            JOptionPane.showMessageDialog(null, "O campo 'Email' possui formato inválido");
            return false;
        }
        if (!edtDataNasc.getText().matches("^[0-3]{1}[0-9]{1}/[0-1]{1}[0-9]{1}/[12]{1}[90]{1}[0-9]{1}[0-9]{1}$")) {
            JOptionPane.showMessageDialog(null, "O campo Data de Nascimento possui formato inválido");
            return false;
        }
        if (edtSenha.isEditable()) {
            if (new String(edtSenha.getPassword()).length() < 6) {
                JOptionPane.showMessageDialog(null, "Senha deve ser maior que 6 digitos");
                return false;
            }

            String senha = new String(edtSenha.getPassword());
            String confirmaSenha = new String(edtConfirmeSenha.getPassword());
            if (!senha.equals(confirmaSenha)) {
                JOptionPane.showMessageDialog(null, "As senhas devem ser iguais e coerentes");
                return false;
            }
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltUsuario dialog = new FrAltUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JPasswordField edtConfirmeSenha;
    private javax.swing.JFormattedTextField edtDataNasc;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblConfirmeSenha;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    // End of variables declaration//GEN-END:variables

}
